<a href="https://colab.research.google.com/github/Ashwini104/Heart-Disease-Prediction/blob/main/heartdisesepredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the dependecies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the csv data to pandas data frame
heart_data = pd.read_csv("heart_disease_data.csv")

In [ ]:
#printing first 5 sets of data
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
#printing last 5 data sets
heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
#number of rows and columns in a data
heart_data.shape

(303, 14)

In [ ]:
#getting information about the data set
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [ ]:
#checking the missing data
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
print(heart_data)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]

In [ ]:
#stastical measures of the data
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

#checking the distribution of target variable
heart_data['target'].value_counts()

In [ ]:
#splitting the data and the target
X = heart_data.drop(columns='target',axis=1)
Y = heart_data['target']

In [ ]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [ ]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

2.splitting the data into training data and testing data

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(303, 13) (242, 13) (61, 13)

3.logistic regression model

In [ ]:
# Convert float columns to int (replace with your actual column names)
float_columns = heart_data.select_dtypes(include=['float64']).columns
for col in float_columns:
    heart_data[col] = heart_data[col].astype(int)

print(heart_data)
print(heart_data.info())

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0        2
1     37    1   2       130   250    0        1      187      0        3
2     41    0   1       130   204    0        0      172      0        1
3     56    1   1       120   236    0        1      178      0        0
4     57    0   0       120   354    0        1      163      1        0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1        0
299   45    1   3       110   264    0        1      132      0        1
300   68    1   0       144   193    1        1      141      0        3
301   57    1   0       130   131    0        1      115      1        1
302   57    0   1       130   236    0        0      174      0        0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    int64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: int64(14)
memory usage: 33.3 KB
None

In [ ]:
#logistic regression model
model = LogisticRegression()

In [ ]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

model evaluation

accuracy score

In [ ]:
#accuracy on train data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
print('accuracy on training data :',training_data_accuracy)

accuracy on training data : 0.8512396694214877

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [ ]:
print('accuracy on test data :',test_data_accuracy)

accuracy on test data : 0.819672131147541

Buildig a Predective system

In [ ]:
input_data=(43,1,0,120,177,0,0,120,1,2.5,1,0,3)
#change the input data into numpy array
input_data_as_numpy_array = np.asarray(input_data)
#reshape the numpy array as we are predicting for only one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

predection =model.predict(input_data_reshaped)
print(predection)

if(predection[0]==0):
  print('the person does not have a heart disease')
else:
  print('the person has heart disease')

[0]
the person does not have a heart disease

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Random forest Classifer

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Training Random Forest Model
rf_model = RandomForestClassifier(random_state=2)
rf_model.fit(X_train, Y_train)

# Accuracy on training data
rf_train_pred = rf_model.predict(X_train)
rf_train_accuracy = accuracy_score(Y_train, rf_train_pred)
print("\nRandom Forest Training Accuracy:", rf_train_accuracy)

# Accuracy on test data
rf_test_pred = rf_model.predict(X_test)
rf_test_accuracy = accuracy_score(Y_test, rf_test_pred)
print("Random Forest Test Accuracy:", rf_test_accuracy)

Random Forest Training Accuracy: 1.0
Random Forest Test Accuracy: 0.7868852459016393

confusion matrix

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create model
rf = RandomForestClassifier(random_state=42)

# Train model
rf.fit(X_train, Y_train)

# Now predict
rf_test_pred = rf.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, rf_test_pred))
print(classification_report(Y_test, rf_test_pred))

[[23  5]
 [ 7 26]]
              precision    recall  f1-score   support

           0       0.77      0.82      0.79        28
           1       0.84      0.79      0.81        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Train Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, Y_train)

# Predictions
X_test_prediction = model.predict(X_test)   # logistic regression
rf_test_pred = rf.predict(X_test)           # random forest

print("\n----- Logistic Regression Evaluation -----")
print("Confusion Matrix:")
print(confusion_matrix(Y_test, X_test_prediction))
print("\nClassification Report:")
print(classification_report(Y_test, X_test_prediction))

print("\n----- Random Forest Evaluation -----")
print("Confusion Matrix:")
print(confusion_matrix(Y_test, rf_test_pred))
print("\nClassification Report:")
print(classification_report(Y_test, rf_test_pred))

----- Logistic Regression Evaluation -----
Confusion Matrix:
[[23  5]
 [ 6 27]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.82      0.81        28
           1       0.84      0.82      0.83        33

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61


----- Random Forest Evaluation -----
Confusion Matrix:
[[23  5]
 [ 7 26]]

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.82      0.79        28
           1       0.84      0.79      0.81        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print("\n----- Logistic Regression Evaluation -----")
print("Confusion Matrix:")
print(confusion_matrix(Y_test, X_test_prediction))
print("\nClassification Report:")
print(classification_report(Y_test, X_test_prediction))

print("\n----- Random Forest Evaluation -----")
print("Confusion Matrix:")
print(confusion_matrix(Y_test, rf_test_pred))
print("\nClassification Report:")
print(classification_report(Y_test, rf_test_pred))

----- Logistic Regression Evaluation -----
Confusion Matrix:
[[23  5]
 [ 6 27]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.82      0.81        28
           1       0.84      0.82      0.83        33

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61


----- Random Forest Evaluation -----
Confusion Matrix:
[[23  5]
 [ 7 26]]

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.82      0.79        28
           1       0.84      0.79      0.81        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

In [ ]:
import pandas as pd

pd.DataFrame(X_train).to_csv("X_train.csv", index=False)
pd.DataFrame(X_test).to_csv("X_test.csv", index=False)
pd.DataFrame(Y_train).to_csv("Y_train.csv", index=False)
pd.DataFrame(Y_test).to_csv("Y_test.csv", index=False)

print("Files saved successfully.")

Files saved successfully.

In [ ]:
from google.colab import files

files.download("X_train.csv")
files.download("X_test.csv")
files.download("Y_train.csv")
files.download("Y_test.csv")